server:
  port: 9090

git:
  url: https://github.com/solivaf/go-maria
  credential:
    username: solivaf
    password: somepassword
  repositories:
    - name: config-properties
      url: git@github.com:solivaf/go-geoffrey.git